services:
  mysql:
    image: 'mysql:latest'
    restart: always
    container_name: mysql-events
    environment:
      - 'MYSQL_DATABASE=db_events'
      - 'MYSQL_ROOT_PASSWORD=admin'
    ports:
      - '3306:3306'
    networks:
      - events-network
networks:
  events-network:
    driver: bridge